services:
  bridge-ui:
    env_file:
      - ./.env
    container_name: "status-network-bridge-ui"
    build:
      args:
        - NEXT_PUBLIC_WALLET_CONNECT_ID=${NEXT_PUBLIC_WALLET_CONNECT_ID}
        - NEXT_PUBLIC_USE_DEVNET=${NEXT_PUBLIC_USE_DEVNET}
        - NEXT_PUBLIC_ETH_RPC_PROXY_USER=${NEXT_PUBLIC_ETH_RPC_PROXY_USER}
        - NEXT_PUBLIC_ETH_RPC_PROXY_PASS=${NEXT_PUBLIC_ETH_RPC_PROXY_PASS}
        - NEXT_PUBLIC_L1_MAINNET_RPC_URL=${NEXT_PUBLIC_L1_MAINNET_RPC_URL}
        - NEXT_PUBLIC_L1_MAINNET_RPC_IS_AUTHENTICATED=${NEXT_PUBLIC_L1_MAINNET_RPC_IS_AUTHENTICATED}
        - NEXT_PUBLIC_L2_MAINNET_RPC_URL=${NEXT_PUBLIC_L2_MAINNET_RPC_URL}
        - NEXT_PUBLIC_L2_MAINNET_RPC_IS_AUTHENTICATED=${NEXT_PUBLIC_L2_MAINNET_RPC_IS_AUTHENTICATED}
        - NEXT_PUBLIC_L1_TESTNET_RPC_URL=${NEXT_PUBLIC_L1_TESTNET_RPC_URL}
        - NEXT_PUBLIC_L1_TESTNET_RPC_IS_AUTHENTICATED=${NEXT_PUBLIC_L1_TESTNET_RPC_IS_AUTHENTICATED}
        - NEXT_PUBLIC_L2_TESTNET_RPC_URL=${NEXT_PUBLIC_L2_TESTNET_RPC_URL}
        - NEXT_PUBLIC_L2_TESTNET_RPC_IS_AUTHENTICATED=${NEXT_PUBLIC_L2_TESTNET_RPC_IS_AUTHENTICATED}
        - NEXT_PUBLIC_L1_DEVNET_RPC_URL=${NEXT_PUBLIC_L1_DEVNET_RPC_URL}
        - NEXT_PUBLIC_L1_DEVNET_RPC_IS_AUTHENTICATED=${NEXT_PUBLIC_L1_DEVNET_RPC_IS_AUTHENTICATED}
        - NEXT_PUBLIC_L2_DEVNET_RPC_URL=${NEXT_PUBLIC_L2_DEVNET_RPC_URL}
        - NEXT_PUBLIC_L2_DEVNET_RPC_IS_AUTHENTICATED=${NEXT_PUBLIC_L2_DEVNET_RPC_IS_AUTHENTICATED}
        - NEXT_PUBLIC_L1_DEVNET_CHAIN_ID=${NEXT_PUBLIC_L1_DEVNET_CHAIN_ID}
        - NEXT_PUBLIC_L2_DEVNET_CHAIN_ID=${NEXT_PUBLIC_L2_DEVNET_CHAIN_ID}
        - NEXT_PUBLIC_USE_PUZZLE_AUTH=${NEXT_PUBLIC_USE_PUZZLE_AUTH}
    ports:
      - 3000:3000